<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Спасибо за регистрацию</title>
    <style>
        h1 {
            color: cadetblue;
        }
        h2 {
            color: red;
        }
    </style>
</head>
<body>
<h1>Ссылка на регистрацию:</h1>
<img src="https://media.kpfu.ru/sites/default/files/2019-08/untitled%20%285%20of%208%29.jpg" alt="">
<h2><a href="http://localhost/confirm/${confirm_code}">Пройдите по ссылке</a></h2>
</body>
</html>
