# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'Kikoff-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Kikoff-ios
  pod 'SwiftLint', '~> 0.46.2'
  pod 'SnapKit', '~> 5.0.0'

end
